# Written by Josh Aldrich and Joseph N. Brown
# for the Department of Energy (PNNL, Richland, WA)
# Battelle Memorial Institute
# E-mail: joseph.brown@pnnl.gov
# Website: http://omics.pnl.gov/software
# -----------------------------------------------------
#
# Notice: This computer software was prepared by Battelle Memorial Institute,
# hereinafter the Contractor, under Contract No. DE-AC05-76RL0 1830 with the
# Department of Energy (DOE).  All rights in the computer software are reserved
# by DOE on behalf of the United States Government and the Contractor as
# provided in the Contract.
#
# NEITHER THE GOVERNMENT NOR THE CONTRACTOR MAKES ANY WARRANTY, EXPRESS OR
# IMPLIED, OR ASSUMES ANY LIABILITY FOR THE USE OF THIS SOFTWARE.
#
# This notice including this sentence must appear on any copies of this computer
# software.
# -----------------------------------------------------#/

################################################################################
## FUNCTIONS
################################################################################

#Calculates a matrix of overlap between fractions of a 2D MSMS run
#Assumes data in a table x with a "Job" column and y denoting the jobs 
#number associated with each fraction preferably in order of fraction
#run.  DoCount is the default which returns intersection counts, when
#set to false it returns the intersection/union of two fractions.
ja_OverlapMatrix <- function(x, y, DoCount = TRUE)
{
    t <- length(y)
    y1 <- matrix(0,t,t)
  y2 <- c()	# vector containing the unique peptides in each fraction
    for(i in 1:t)
    {
        for(j in i:t)
        {
            xx1 <- x[x[,"Fraction"]==y[i],]
            xx2 <- x[x[,"Fraction"]==y[j],]
            if(DoCount)
            {
                xx3 <- intersect(xx1[,"Peptide"],xx2[,"Peptide"])   
                xx4 <- 1

            }
            else
            {
                xx3 <- intersect(xx1[,"Peptide"],xx2[,"Peptide"])
                xx4 <- union(xx1[,"Peptide"],xx2[,"Peptide"])
            }

            
            y1[i,j] = length(xx3)/length(xx4)
            y1[j,i] = y1[i,j]
        }
		y2 <- c(y2, y1[i,i])
    }
    ol <- c()
    if (dim(y1)[1] == dim(y1)[2])
    {
      for (i in 2:dim(y1)[1])
      {
        j <- i - 1
        ol <- c(ol, y1[j,i])
      }
    }
    
    y1.1 <- y1
    for (i in 1:dim(y1.1)[1])
    {
      y1.1[i,i] <- 0
    }
    
	y3 <- list(myMatrix=y1, myMatrix1=y1.1, myPeptides=y2, Overlap=ol,
             totalPeptides=length(unique(unlist(subset(x, select=c("Peptide"))))))
    return(y3)
}

#My preferred heatmap function
ja_MyHeat <- function(zz)
{
    require(gplots)
    heatmap.2(zz, Rowv = NA, Colv = NA, dendrogram = "none", 
            trace = "none", linecol = "blue", main = "Fraction Overlap")
}

# Traverses through the table generated by overlapMatrix, and grabs the unique
# peptide counts (diagonal) for each fraction
jnb_GetUniquePeptideCountsForFractions <- function(x)
{
	pep2return <- c()
	# x must be a perfect square
	if (dim(x)[1] == dim(x)[2])
	{
		for (i in 1:dim(x)[1])
		{
			pep2return <- c(pep2return, x[i,i])
		}
	}
	return(pep2return)
}
